[supervisord]

[program:web]
command=sh -c "php -S 0.0.0.0:${PORT:-8000} -t public"
autostart=true
autorestart=true

# [program:cron]
# command=cron -f
# autostart=true
# autorestart=true
[program:scheduler]
command=php artisan schedule:work
autostart=true
autorestart=true